name: Executar Script de Python

on:
  schedule:
    #- cron: '0 8,10,12,14,16,18 * * 1-5'  # Executa a les 9, 11, 13, 15, 17 i 19 UTC+1
    - cron: '5 * * * 1-5'  # Executa a les 9, 11, 13, 15, 17 i 19 UTC+1

jobs:
  executar_script:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositori
      uses: actions/checkout@v3  # Acció per clonar el repositori

    - name: Configurar Python
      uses: actions/setup-python@v4  # Acció per configurar Python
      with:
        python-version: '3.9'  # Especifica la versió de Python

    - name: Instal·lar les dependències
      run: |
        pip install -r requirements.txt

    - name: Instal·lar Playwright i els navegadors
      run: |
        playwright install-deps
        playwright install

    - name: Executar el script
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        WORKSHEET_KEY: ${{ secrets.WORKSHEET_KEY }}
      run: |
        python scrap_playwright.py
